# Generated by Django 3.2.12 on 2023-01-26 23:23

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_title_i_377c08_idx',
        ),
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_nlm_tit_c1aab6_idx',
        ),
        migrations.RemoveIndex(
            model_name='officialjournal',
            name='journal_off_foundat_adccd1_idx',
        ),
        migrations.RemoveField(
            model_name='officialjournal',
            name='nlm_title',
        ),
        migrations.RemoveField(
            model_name='officialjournal',
            name='title_iso',
        ),
        migrations.AddField(
            model_name='journal',
            name='nlm_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='NLM Title'),
        ),
        migrations.AddField(
            model_name='officialjournal',
            name='foundation_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Foundation Day'),
        ),
        migrations.AddField(
            model_name='officialjournal',
            name='foundation_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Foundation Month'),
        ),
        migrations.AddField(
            model_name='officialjournal',
            name='foundation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Foundation Year'),
        ),
        migrations.AlterField(
            model_name='editorialmanager',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorialmanager', to='journal.journal'),
        ),
        migrations.AlterField(
            model_name='fieldmission',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission', to='journal.journalmission'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='official_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='journal.officialjournal'),
        ),
        migrations.AlterField(
            model_name='journalmission',
            name='official_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='JournalMission_OfficialJournal', to='journal.officialjournal'),
        ),
        migrations.AlterField(
            model_name='journalsocialnetwork',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journalsocialnetwork', to='journal.journal'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission', to='journal.journal'),
        ),
        migrations.AlterField(
            model_name='nonofficialjournaltitle',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='nonofficialjournaltitle_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='nonofficialjournaltitle',
            name='official_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OfficialJournal', to='journal.officialjournal'),
        ),
        migrations.AlterField(
            model_name='nonofficialjournaltitle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonofficialjournaltitle_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AlterField(
            model_name='officialjournal',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='officialjournal_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='officialjournal',
            name='short_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ISO Short Title'),
        ),
        migrations.AlterField(
            model_name='officialjournal',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officialjournal_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='journal.journal'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher', to='journal.journal'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor', to='journal.journal'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['official_journal'], name='journal_jou_officia_2d61d0_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['short_title'], name='journal_jou_short_t_37385e_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['nlm_title'], name='journal_jou_nlm_tit_74bf49_idx'),
        ),
        migrations.AddIndex(
            model_name='officialjournal',
            index=models.Index(fields=['foundation_year'], name='journal_off_foundat_fcc7eb_idx'),
        ),
    ]
