# Generated by Django 5.0.3 on 2024-05-17 02:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_journal_journal_acron"),
        ("journal", "0003_journal_submission_online_url_sponsor_subject_and_more"),
    ]

    operations = []
