# Generated by Django 5.0.3 on 2024-09-02 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0004_journal_contact_address_journal_contact_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="official_journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.officialjournal",
            ),
        ),
    ]
