# Generated by Django 5.0.3 on 2024-05-17 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0003_websiteconfigurationendpoint"),
        ("journal", "0004_merge_20240517_0229"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mission",
            new_name="journal_mis_languag_a94f2f_idx",
            old_name="journal_mis_languag_bfebee_idx",
        ),
        migrations.AlterField(
            model_name="mission",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collection.language",
            ),
        ),
    ]
