# Generated by Django 5.0.3 on 2025-03-01 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0007_journal_wos_areas"),
        ("journal", "0007_merge_20241113_1945"),
    ]

    operations = []
