# Generated by Django 5.0.3 on 2024-06-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("package", "0002_alter_spspkg_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spspkg",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[("MIGRATION", "MIGRATION"), ("UPLOAD", "UPLOAD")],
                max_length=32,
                null=True,
            ),
        ),
    ]
