# Generated by Django 3.2.12 on 2022-09-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='periodictask',
            index=models.Index(fields=['name'], name='django_cele_name_9c39ec_idx'),
        ),
        migrations.AddIndex(
            model_name='periodictask',
            index=models.Index(fields=['task'], name='django_cele_task_25431b_idx'),
        ),
    ]
