# Generated by Django 3.2.12 on 2023-01-26 23:23

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='city_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AlterField(
            model_name='country',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='country_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='location_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AlterField(
            model_name='state',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='state_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
    ]
