# Generated by Django 5.2.3 on 2026-08-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("htmlxml", "0005_remove_duplicate_htmlxml_and_add_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodyandbackfile",
            name="xml_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="htmlxml",
            name="xml_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
