# Generated by Django 3.2.12 on 2023-01-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230126_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code2',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Language code 2'),
        ),
    ]
