# Generated by Django 3.2.12 on 2022-09-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicwebsiteconfiguration',
            name='serial_path',
            field=models.CharField(blank=True, help_text='Serial path', max_length=255, null=True, verbose_name='Serial path'),
        ),
    ]
