# Generated by Django 3.2.12 on 2022-09-22 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('collection', '0002_classicwebsiteconfiguration_serial_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentincollections',
            name='official_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article'),
        ),
        migrations.AddIndex(
            model_name='documentincollections',
            index=models.Index(fields=['official_document'], name='collection__officia_d8e170_idx'),
        ),
    ]
