# Generated by Django 5.0.3 on 2024-05-22 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0003_websiteconfigurationendpoint"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebSiteConfigurationEndpoint",
        ),
    ]
