# Generated by Django 3.2.12 on 2022-09-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20220922_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesstorageconfiguration',
            name='bucket_migration_subdir',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Bucket migration subdir'),
        ),
        migrations.AlterField(
            model_name='filesstorageconfiguration',
            name='bucket_public_subdir',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Bucket public subdir'),
        ),
        migrations.AlterField(
            model_name='filesstorageconfiguration',
            name='bucket_subdir',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Bucket subdir'),
        ),
        migrations.AlterField(
            model_name='filesstorageconfiguration',
            name='bucket_temp_subdir',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Bucket temp subdir'),
        ),
        migrations.AlterField(
            model_name='filesstorageconfiguration',
            name='bucket_versions_subdir',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Bucket versions subdir'),
        ),
        migrations.AlterField(
            model_name='scielojournal',
            name='publication_status',
            field=models.CharField(blank=True, choices=[('C', 'Current')], max_length=10, null=True, verbose_name='Publication Status'),
        ),
    ]
