# Generated by Django 3.2.12 on 2022-09-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20220923_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesstorageconfiguration',
            name='secure',
            field=models.BooleanField(default=True, verbose_name='Secure'),
        ),
    ]
