# Generated by Django 3.2.12 on 2022-09-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_filesstorageconfiguration_secure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scielodocument',
            name='pid',
            field=models.CharField(blank=True, max_length=23, null=True, verbose_name='PID'),
        ),
    ]
