# Generated by Django 3.2.12 on 2023-01-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20221231_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scielodocument',
            name='html_files',
            field=models.ManyToManyField(related_name='html_files', to='collection.SciELOHTMLFile'),
        ),
        migrations.AlterField(
            model_name='scielodocument',
            name='rendition_files',
            field=models.ManyToManyField(related_name='rendition_files', to='collection.FileWithLang'),
        ),
        migrations.AlterField(
            model_name='scielodocument',
            name='xml_files',
            field=models.ManyToManyField(related_name='xml_files', to='collection.XMLFile'),
        ),
    ]
