# Generated by Django 3.2.12 on 2023-01-26 23:23

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researcher', '0002_auto_20230123_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldaffiliation',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliation', to='researcher.researcher'),
        ),
        migrations.AlterField(
            model_name='fieldemail',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_email', to='researcher.researcher'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='researcher_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researcher_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
    ]
