# Generated by Django 3.2.18 on 2023-05-04 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pid_requester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PidProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('pid_provider_api_post_xml', models.TextField(blank=True, null=True, verbose_name='XML Post URI')),
                ('pid_provider_api_get_token', models.TextField(blank=True, null=True, verbose_name='Get Token URI')),
                ('timeout', models.IntegerField(blank=True, null=True, verbose_name='Timeout')),
                ('api_username', models.TextField(blank=True, null=True, verbose_name='API Username')),
                ('api_password', models.TextField(blank=True, null=True, verbose_name='API Password')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pidproviderconfig_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pidproviderconfig_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
