# Generated by Django 3.2.12 on 2023-02-20 03:54

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issue', '0001_initial'),
        ('files_storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('collection', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyAndBackXMLFile',
            fields=[
                ('miniofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files_storage.miniofile')),
                ('selected', models.BooleanField(default=False)),
                ('version', models.IntegerField(blank=True, null=True, verbose_name='Version')),
            ],
            options={
                'abstract': False,
            },
            bases=('files_storage.miniofile',),
        ),
        migrations.CreateModel(
            name='MigratedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('isis_updated_date', models.TextField(blank=True, max_length=8, null=True, verbose_name='ISIS updated date')),
                ('isis_created_date', models.TextField(blank=True, max_length=8, null=True, verbose_name='ISIS created date')),
                ('data', models.JSONField(blank=True, null=True)),
                ('status', models.TextField(choices=[('TO_MIGRATE', 'To migrate'), ('TO_IGNORE', 'To ignore'), ('IMPORTED', 'Imported'), ('PUBLISHED', 'Publicado')], default='TO_MIGRATE', verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='MigratedFile',
            fields=[
                ('miniofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files_storage.miniofile')),
                ('pkg_name', models.TextField(blank=True, null=True, verbose_name='Package name')),
                ('relative_path', models.TextField(blank=True, null=True, verbose_name='Relative Path')),
            ],
            bases=('files_storage.miniofile',),
        ),
        migrations.CreateModel(
            name='MigratedAssetFile',
            fields=[
                ('migratedfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.migratedfile')),
            ],
            options={
                'abstract': False,
            },
            bases=('migration.migratedfile',),
        ),
        migrations.CreateModel(
            name='MigratedDocument',
            fields=[
                ('migrateddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.migrateddata')),
                ('v3', models.TextField(blank=True, max_length=23, null=True, verbose_name='PID v3')),
                ('pid', models.TextField(blank=True, max_length=23, null=True, verbose_name='PID v2')),
                ('aop_pid', models.TextField(blank=True, max_length=23, null=True, verbose_name='AOP PID')),
                ('pkg_name', models.TextField(blank=True, null=True, verbose_name='Package name')),
                ('files_status', models.TextField(choices=[('TO_MIGRATE', 'To migrate'), ('TO_IGNORE', 'To ignore'), ('IMPORTED', 'Imported'), ('PUBLISHED', 'Publicado')], default='TO_MIGRATE', verbose_name='Status')),
            ],
            bases=('migration.migrateddata',),
        ),
        migrations.CreateModel(
            name='MigratedHTMLFile',
            fields=[
                ('migratedfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.migratedfile')),
                ('part', models.TextField(verbose_name='Part')),
                ('replacements', models.JSONField(blank=True, null=True)),
            ],
            bases=('migration.migratedfile',),
        ),
        migrations.CreateModel(
            name='MigratedIssue',
            fields=[
                ('migrateddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.migrateddata')),
                ('issue_pid', models.TextField(max_length=23, verbose_name='Issue PID')),
                ('issue_folder', models.TextField(max_length=23, verbose_name='Issue Folder')),
                ('files_status', models.TextField(choices=[('TO_MIGRATE', 'To migrate'), ('TO_IGNORE', 'To ignore'), ('IMPORTED', 'Imported'), ('PUBLISHED', 'Publicado')], default='TO_MIGRATE', verbose_name='Status')),
                ('files', models.JSONField(blank=True, null=True)),
            ],
            bases=('migration.migrateddata',),
        ),
        migrations.CreateModel(
            name='MigratedJournal',
            fields=[
                ('migrateddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.migrateddata')),
                ('scielo_issn', models.TextField(max_length=9, verbose_name='SciELO ISSN')),
                ('acron', models.TextField(blank=True, null=True, verbose_name='Acronym')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Title')),
                ('availability_status', models.TextField(blank=True, choices=[('?', 'Unknown'), ('C', 'Current')], null=True, verbose_name='Availability Status')),
            ],
            bases=('migration.migrateddata',),
        ),
        migrations.CreateModel(
            name='MigratedPdfFile',
            fields=[
                ('migratedfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.migratedfile')),
            ],
            bases=('migration.migratedfile',),
        ),
        migrations.CreateModel(
            name='MigratedXMLFile',
            fields=[
                ('migratedfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.migratedfile')),
            ],
            options={
                'abstract': False,
            },
            bases=('migration.migratedfile',),
        ),
        migrations.CreateModel(
            name='MigrationFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('action_name', models.TextField(blank=True, null=True, verbose_name='Action')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('exception_type', models.TextField(blank=True, null=True, verbose_name='Exception Type')),
                ('exception_msg', models.TextField(blank=True, null=True, verbose_name='Exception Msg')),
                ('traceback', models.JSONField(blank=True, null=True)),
                ('creator', models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='migrationfailure_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrationfailure_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.CreateModel(
            name='MigrationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('classic_website_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.classicwebsiteconfiguration', verbose_name='Classic website configuration')),
                ('creator', models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='migrationconfiguration_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('migration_files_storage_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_files_storage_config', to='files_storage.minioconfiguration', verbose_name='Migration Files Storage Configuration')),
                ('new_website_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.newwebsiteconfiguration', verbose_name='New website configuration')),
                ('public_files_storage_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_files_storage_config', to='files_storage.minioconfiguration', verbose_name='Public Files Storage Configuration')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrationconfiguration_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.AddIndex(
            model_name='migratedfile',
            index=models.Index(fields=['pkg_name'], name='migration_m_pkg_nam_488997_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedfile',
            index=models.Index(fields=['relative_path'], name='migration_m_relativ_e4b229_idx'),
        ),
        migrations.AddField(
            model_name='migrateddata',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='migrateddata_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='migrateddata',
            name='failures',
            field=models.ManyToManyField(to='migration.MigrationFailure'),
        ),
        migrations.AddField(
            model_name='migrateddata',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrateddata_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddIndex(
            model_name='migrationfailure',
            index=models.Index(fields=['action_name'], name='migration_m_action__031324_idx'),
        ),
        migrations.AddIndex(
            model_name='migrationconfiguration',
            index=models.Index(fields=['classic_website_config'], name='migration_m_classic_518e10_idx'),
        ),
        migrations.AddField(
            model_name='migratedxmlfile',
            name='assets_files',
            field=models.ManyToManyField(to='migration.MigratedAssetFile'),
        ),
        migrations.AddField(
            model_name='migratedpdffile',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language'),
        ),
        migrations.AddField(
            model_name='migratedjournal',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.collection'),
        ),
        migrations.AddField(
            model_name='migratedjournal',
            name='official_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.officialjournal'),
        ),
        migrations.AddField(
            model_name='migratedissue',
            name='assets',
            field=models.ManyToManyField(related_name='issue_assets', to='migration.MigratedAssetFile'),
        ),
        migrations.AddField(
            model_name='migratedissue',
            name='htmls',
            field=models.ManyToManyField(related_name='issue_htmls', to='migration.MigratedHTMLFile'),
        ),
        migrations.AddField(
            model_name='migratedissue',
            name='migrated_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='migration.migratedjournal'),
        ),
        migrations.AddField(
            model_name='migratedissue',
            name='official_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issue.issue'),
        ),
        migrations.AddField(
            model_name='migratedissue',
            name='pdfs',
            field=models.ManyToManyField(related_name='issue_pdfs', to='migration.MigratedPdfFile'),
        ),
        migrations.AddField(
            model_name='migratedissue',
            name='xmls',
            field=models.ManyToManyField(related_name='issue_xmls', to='migration.MigratedXMLFile'),
        ),
        migrations.AddField(
            model_name='migratedhtmlfile',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language'),
        ),
        migrations.AddField(
            model_name='migrateddocument',
            name='body_and_back_xmls',
            field=models.ManyToManyField(to='migration.BodyAndBackXMLFile'),
        ),
        migrations.AddField(
            model_name='migrateddocument',
            name='htmls',
            field=models.ManyToManyField(related_name='htmls', to='migration.MigratedHTMLFile'),
        ),
        migrations.AddField(
            model_name='migrateddocument',
            name='main_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language'),
        ),
        migrations.AddField(
            model_name='migrateddocument',
            name='migrated_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='migration.migratedissue'),
        ),
        migrations.AddField(
            model_name='migrateddocument',
            name='pdfs',
            field=models.ManyToManyField(related_name='pdfs', to='migration.MigratedPdfFile'),
        ),
        migrations.AddField(
            model_name='migrateddocument',
            name='xmls',
            field=models.ManyToManyField(related_name='xmls', to='migration.MigratedXMLFile'),
        ),
        migrations.AddIndex(
            model_name='migrateddata',
            index=models.Index(fields=['isis_updated_date'], name='migration_m_isis_up_c84dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='migrateddata',
            index=models.Index(fields=['status'], name='migration_m_status_9aee95_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedpdffile',
            index=models.Index(fields=['lang'], name='migration_m_lang_id_86e459_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedjournal',
            index=models.Index(fields=['acron'], name='migration_m_acron_e532c4_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedjournal',
            index=models.Index(fields=['collection'], name='migration_m_collect_5e7ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedjournal',
            index=models.Index(fields=['scielo_issn'], name='migration_m_scielo__7cd3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedjournal',
            index=models.Index(fields=['availability_status'], name='migration_m_availab_7567e1_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedjournal',
            index=models.Index(fields=['official_journal'], name='migration_m_officia_3371a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='migratedjournal',
            unique_together={('collection', 'acron'), ('collection', 'scielo_issn')},
        ),
        migrations.AddIndex(
            model_name='migratedissue',
            index=models.Index(fields=['migrated_journal'], name='migration_m_migrate_867c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedissue',
            index=models.Index(fields=['official_issue'], name='migration_m_officia_de23ae_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedissue',
            index=models.Index(fields=['issue_pid'], name='migration_m_issue_p_c1f81b_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedissue',
            index=models.Index(fields=['issue_folder'], name='migration_m_issue_f_e732cc_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedissue',
            index=models.Index(fields=['files_status'], name='migration_m_files_s_5ed1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedhtmlfile',
            index=models.Index(fields=['lang'], name='migration_m_lang_id_fdebc6_idx'),
        ),
        migrations.AddIndex(
            model_name='migratedhtmlfile',
            index=models.Index(fields=['part'], name='migration_m_part_d5b273_idx'),
        ),
        migrations.AddIndex(
            model_name='migrateddocument',
            index=models.Index(fields=['migrated_issue'], name='migration_m_migrate_db24e4_idx'),
        ),
        migrations.AddIndex(
            model_name='migrateddocument',
            index=models.Index(fields=['v3'], name='migration_m_v3_46ab97_idx'),
        ),
        migrations.AddIndex(
            model_name='migrateddocument',
            index=models.Index(fields=['pid'], name='migration_m_pid_9c9c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='migrateddocument',
            index=models.Index(fields=['aop_pid'], name='migration_m_aop_pid_136bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='migrateddocument',
            index=models.Index(fields=['pkg_name'], name='migration_m_pkg_nam_2bd7db_idx'),
        ),
        migrations.AddIndex(
            model_name='migrateddocument',
            index=models.Index(fields=['files_status'], name='migration_m_files_s_49b576_idx'),
        ),
    ]
