# Generated by Django 3.2.12 on 2022-09-17 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MigratedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('isis_updated_date', models.CharField(blank=True, max_length=8, null=True, verbose_name='ISIS updated date')),
                ('isis_created_date', models.CharField(blank=True, max_length=8, null=True, verbose_name='ISIS created date')),
                ('data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TO_MIGRATE', 'To migrate'), ('MIGRATED', 'Migrated'), ('PUBLISHED', 'Publicado')], default='TO_MIGRATE', max_length=20, verbose_name='Status')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migrateddata_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migrateddata_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SciELOFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('file_id', models.CharField(max_length=255, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Filename')),
                ('uri', models.CharField(max_length=255, null=True, verbose_name='URI')),
                ('object_name', models.CharField(max_length=255, null=True, verbose_name='Object name')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='scielofile_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scielofile_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SciELOFileWithLang',
            fields=[
                ('scielofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.scielofile')),
                ('lang', models.CharField(max_length=2, verbose_name='Language')),
            ],
            options={
                'abstract': False,
            },
            bases=('migration.scielofile',),
        ),
        migrations.CreateModel(
            name='MigrationFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('action_name', models.CharField(max_length=255, verbose_name='Action')),
                ('object_name', models.CharField(max_length=255, verbose_name='Object')),
                ('pid', models.CharField(max_length=23, verbose_name='Item PID')),
                ('exception_type', models.CharField(max_length=255, verbose_name='Exception Type')),
                ('exception_msg', models.CharField(max_length=255, verbose_name='Exception Msg')),
                ('traceback', models.JSONField(blank=True, null=True)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='migrationfailure_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='migrationfailure_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseFilesMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('status', models.CharField(choices=[('TO_MIGRATE', 'To migrate'), ('MIGRATED', 'Migrated'), ('PUBLISHED', 'Publicado')], default='TO_MIGRATE', max_length=20, verbose_name='Status')),
                ('assets', models.ManyToManyField(blank=True, related_name='assets', to='migration.SciELOFile')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='basefilesmigration_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basefilesmigration_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
                ('xmls', models.ManyToManyField(blank=True, related_name='xmls', to='migration.SciELOFile')),
                ('pdfs', models.ManyToManyField(blank=True, related_name='pdfs', to='migration.SciELOFileWithLang')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SciELOHTMLFile',
            fields=[
                ('scielofilewithlang_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.scielofilewithlang')),
                ('part', models.CharField(max_length=5, verbose_name='Part')),
            ],
            options={
                'abstract': False,
            },
            bases=('migration.scielofilewithlang',),
        ),
        migrations.CreateModel(
            name='JournalMigration',
            fields=[
                ('migrateddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.migrateddata')),
                ('scielo_journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.scielojournal')),
            ],
            options={
                'abstract': False,
            },
            bases=('migration.migrateddata',),
        ),
        migrations.CreateModel(
            name='IssueMigration',
            fields=[
                ('migrateddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.migrateddata')),
                ('scielo_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.scieloissue')),
            ],
            options={
                'abstract': False,
            },
            bases=('migration.migrateddata',),
        ),
        migrations.CreateModel(
            name='IssueFilesMigration',
            fields=[
                ('basefilesmigration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.basefilesmigration')),
                ('scielo_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.scieloissue')),
            ],
            options={
                'abstract': False,
            },
            bases=('migration.basefilesmigration',),
        ),
        migrations.CreateModel(
            name='DocumentMigration',
            fields=[
                ('migrateddata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.migrateddata')),
                ('scielo_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.scielodocument')),
            ],
            options={
                'abstract': False,
            },
            bases=('migration.migrateddata',),
        ),
        migrations.CreateModel(
            name='DocumentFilesMigration',
            fields=[
                ('basefilesmigration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='migration.basefilesmigration')),
                ('scielo_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.scielodocument')),
                ('suppl_mats', models.ManyToManyField(blank=True, related_name='suppl_mats', to='migration.SciELOFile')),
            ],
            options={
                'abstract': False,
            },
            bases=('migration.basefilesmigration',),
        ),
        migrations.AddField(
            model_name='basefilesmigration',
            name='htmls',
            field=models.ManyToManyField(blank=True, related_name='htmls', to='migration.SciELOHTMLFile'),
        ),
    ]
