# Generated by Django 3.2.12 on 2022-09-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationfailure',
            name='exception_msg',
            field=models.CharField(max_length=555, verbose_name='Exception Msg'),
        ),
    ]
