# Generated by Django 3.2.12 on 2023-01-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrateddocument',
            name='v3',
            field=models.CharField(blank=True, max_length=23, null=True, verbose_name='PID v3'),
        ),
        migrations.AlterField(
            model_name='migrateddocument',
            name='pid',
            field=models.CharField(blank=True, max_length=23, null=True, verbose_name='PID v2'),
        ),
    ]
