# Generated by Django 3.2.12 on 2023-02-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0002_auto_20230221_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrateddocument',
            name='htmls',
            field=models.ManyToManyField(to='migration.MigratedHTMLFile'),
        ),
        migrations.AlterField(
            model_name='migrateddocument',
            name='pdfs',
            field=models.ManyToManyField(to='migration.MigratedPdfFile'),
        ),
        migrations.AlterField(
            model_name='migrateddocument',
            name='xmls',
            field=models.ManyToManyField(to='migration.MigratedXMLFile'),
        ),
    ]
