# Generated by Django 3.2.12 on 2023-01-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_storage', '0001_initial'),
        ('migration', '0002_auto_20230129_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrateddocument',
            name='html_files',
        ),
        migrations.RemoveField(
            model_name='migrateddocument',
            name='rendition_files',
        ),
        migrations.RemoveField(
            model_name='migrateddocument',
            name='xml_body_files',
        ),
        migrations.RemoveField(
            model_name='migrateddocument',
            name='xml_files',
        ),
        migrations.AddField(
            model_name='migrateddocument',
            name='body_xmls',
            field=models.ManyToManyField(related_name='body_xmls', to='files_storage.BodyAndBackXMLFile'),
        ),
        migrations.AddField(
            model_name='migrateddocument',
            name='htmls',
            field=models.ManyToManyField(related_name='htmls', to='files_storage.SciELOHTMLFile'),
        ),
        migrations.AddField(
            model_name='migrateddocument',
            name='pdfs',
            field=models.ManyToManyField(related_name='pdfs', to='files_storage.FileWithLang'),
        ),
        migrations.AddField(
            model_name='migrateddocument',
            name='xmls',
            field=models.ManyToManyField(related_name='xmls', to='files_storage.XMLFile'),
        ),
        migrations.AlterField(
            model_name='migratedissue',
            name='assets',
            field=models.ManyToManyField(related_name='issue_assets', to='files_storage.AssetFile'),
        ),
        migrations.AlterField(
            model_name='migratedissue',
            name='htmls',
            field=models.ManyToManyField(related_name='issue_htmls', to='files_storage.SciELOHTMLFile'),
        ),
        migrations.AlterField(
            model_name='migratedissue',
            name='pdfs',
            field=models.ManyToManyField(related_name='issue_pdfs', to='files_storage.FileWithLang'),
        ),
        migrations.AlterField(
            model_name='migratedissue',
            name='xmls',
            field=models.ManyToManyField(related_name='issue_xmls', to='files_storage.XMLFile'),
        ),
    ]
