# Generated by Django 3.2.12 on 2023-01-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0003_auto_20230129_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrateddocument',
            name='aop_pid',
            field=models.CharField(blank=True, max_length=23, null=True, verbose_name='AOP PID'),
        ),
    ]
