# Generated by Django 5.0.3 on 2024-09-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basexmlvalidationresult",
            name="focus",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Focus on"
            ),
        ),
        migrations.AlterField(
            model_name="basexmlvalidationresult",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="Item being analyzed",
                max_length=128,
                null=True,
                verbose_name="Subject",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="linked",
            field=models.ManyToManyField(
                help_text="Related packages which will be published only if all are approved",
                to="upload.package",
            ),
        ),
        migrations.AlterField(
            model_name="pkgvalidationresult",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="Item being analyzed",
                max_length=128,
                null=True,
                verbose_name="Subject",
            ),
        ),
    ]
