# Generated by Django 5.0.3 on 2024-09-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0002_alter_basexmlvalidationresult_focus_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package",
            old_name="critical_errors",
            new_name="blocking_errors",
        ),
        migrations.AlterField(
            model_name="basexmlvalidationresult",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLOCKING", "blocking"),
                    ("CRITICAL", "critical"),
                    ("ERROR", "error"),
                    ("UKN", "unknown"),
                    ("WARNING", "warning"),
                    ("OK", "ok"),
                ],
                default="UKN",
                max_length=8,
                null=True,
                verbose_name="Result",
            ),
        ),
        migrations.AlterField(
            model_name="pkgvalidationresult",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLOCKING", "blocking"),
                    ("CRITICAL", "critical"),
                    ("ERROR", "error"),
                    ("UKN", "unknown"),
                    ("WARNING", "warning"),
                    ("OK", "ok"),
                ],
                default="UKN",
                max_length=8,
                null=True,
                verbose_name="Result",
            ),
        ),
        migrations.AlterField(
            model_name="uploadvalidator",
            name="decision_for_critical_errors",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending-correction", "Pending for correction"),
                    ("validated-with-errors", "Validated with errors"),
                ],
                default="pending-correction",
                max_length=32,
                null=True,
            ),
        ),
    ]
