# Generated by Django 5.0.3 on 2024-05-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0002_basexmlvalidationresult_package_blocking_errors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="xmlerrorreport",
            name="total_absent_data",
        ),
        migrations.RemoveField(
            model_name="xmlerrorreport",
            name="total_not_to_fix",
        ),
        migrations.RemoveField(
            model_name="xmlerrorreport",
            name="total_to_fix",
        ),
        migrations.AddField(
            model_name="package",
            name="percentual_xml_errors_declared_absent_data",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="package",
            name="percentual_xml_errors_declared_not_to_fix",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="package",
            name="percentual_xml_errors_declared_to_fix",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="xmlerrorreport",
            name="xml_producer_ack",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="The XML producer confirmed being notified of the errors and then added comments.",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submetido"),
                    ("enqueued-for-validation", "Enqueued for validation"),
                    ("validated-with-errors", "Validated with errors"),
                    ("approved-with-errors", "Approved with errors"),
                    ("pending-correction", "Pending for correction"),
                    ("pending-deposit", "Pending deposit"),
                    ("pending-qa-decision", "Pending quality analysis decision"),
                    ("pending-correction", "Pending for correction"),
                    ("rejected", "Rejeitado"),
                    ("approved", "Aprovado"),
                    ("scheduled-for-publication", "Scheduled for publication"),
                    ("published", "Publicado"),
                ],
                default="enqueued-for-validation",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="validationreport",
            name="conclusion",
            field=models.CharField(
                choices=[
                    ("done", "done"),
                    ("doing", "doing"),
                    ("", ""),
                    ("to-review", "to-review"),
                ],
                default="",
                max_length=16,
                verbose_name="conclusion",
            ),
        ),
        migrations.AlterField(
            model_name="xmlerrorreport",
            name="conclusion",
            field=models.CharField(
                choices=[
                    ("done", "done"),
                    ("doing", "doing"),
                    ("", ""),
                    ("to-review", "to-review"),
                ],
                default="",
                max_length=16,
                verbose_name="conclusion",
            ),
        ),
        migrations.AlterField(
            model_name="xmlinforeport",
            name="conclusion",
            field=models.CharField(
                choices=[
                    ("done", "done"),
                    ("doing", "doing"),
                    ("", ""),
                    ("to-review", "to-review"),
                ],
                default="",
                max_length=16,
                verbose_name="conclusion",
            ),
        ),
    ]
