# Generated by Django 5.0.3 on 2024-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0002_basexmlvalidationresult_pkgvalidationresult_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="pid_v2",
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submetido"),
                    ("enqueued-for-validation", "Enqueued for validation"),
                    ("validated-with-errors", "Validated with errors"),
                    ("approved-with-errors", "Approved with errors"),
                    ("pending-correction", "Pending for correction"),
                    ("pending-deposit", "Pending deposit"),
                    ("pending-qa-decision", "Pending quality analysis decision"),
                    ("pending-correction", "Pending for correction"),
                    ("rejected", "Rejeitado"),
                    ("approved", "Aprovado"),
                    ("prepare-sps-pkg", "Preparing SPS package"),
                    ("prepare-publication", "Prepare publication"),
                    ("ready-to-qa", "Ready to QA website"),
                    ("ready-to-publish", "Ready to publish"),
                    ("scheduled-publication", "Scheduled publication"),
                    ("published", "Publicado"),
                ],
                default="enqueued-for-validation",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
