# Generated by Django 5.0.3 on 2024-05-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "upload",
            "0003_basexmlvalidationresult_package_journal_package_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="blocking_errors",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="package",
            name="errors",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="package",
            name="percentual",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="package",
            name="validations",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
