# Generated by Django 5.0.3 on 2024-05-26 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
        ("issue", "0002_alter_issue_number_alter_issue_supplement_and_more"),
        ("journal", "0004_remove_journal_journal_acron_and_more"),
        ("upload", "0003_remove_xmlerrorreport_total_absent_data_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="xmlerrorreport",
            options={
                "verbose_name": "XML Error Report",
                "verbose_name_plural": "XML Error Reports",
            },
        ),
        migrations.RemoveIndex(
            model_name="xmlerrorreport",
            name="upload_xmle_title_32a640_idx",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="percentual",
            new_name="error_percentage",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="percentual_xml_errors_declared_absent_data",
            new_name="xml_errors_declared_absent_data_percentage",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="percentual_xml_errors_declared_not_to_fix",
            new_name="xml_errors_declared_not_to_fix_percentage",
        ),
        migrations.RenameField(
            model_name="package",
            old_name="percentual_xml_errors_declared_to_fix",
            new_name="xml_errors_declared_to_fix_percentage",
        ),
        migrations.AlterUniqueTogether(
            name="xmlerrorreport",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["category"], name="upload_pack_categor_3c1eb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["name"], name="upload_pack_name_97273b_idx"),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["validations"], name="upload_pack_validat_f6a140_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["expiration_date"], name="upload_pack_expirat_ecdd26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["status"], name="upload_pack_status_12c5cd_idx"),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["qa_decision"], name="upload_pack_qa_deci_da84e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["blocking_errors"], name="upload_pack_blockin_39ecda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["errors"], name="upload_pack_errors_473870_idx"),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["warnings"], name="upload_pack_warning_27cd2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["error_percentage"], name="upload_pack_error_p_7dd877_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["xml_errors_declared_to_fix_percentage"],
                name="upload_pack_xml_err_c1ec59_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["xml_errors_declared_not_to_fix_percentage"],
                name="upload_pack_xml_err_f33838_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["xml_errors_declared_absent_data_percentage"],
                name="upload_pack_xml_err_d77622_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationreport",
            index=models.Index(
                fields=["conclusion"], name="upload_vali_conclus_05f8db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationreport",
            index=models.Index(
                fields=["category"], name="upload_vali_categor_5773a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="xmlerror",
            index=models.Index(
                fields=["error_level"], name="upload_xmle_error_l_66d358_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="xmlerrorreport",
            index=models.Index(
                fields=["xml_producer_ack"], name="upload_xmle_xml_pro_58d37e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="xmlinforeport",
            index=models.Index(
                fields=["conclusion"], name="upload_xmli_conclus_c1af95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="xmlinforeport",
            index=models.Index(
                fields=["category"], name="upload_xmli_categor_694408_idx"
            ),
        ),
    ]
