# Generated by Django 5.0.3 on 2024-06-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0003_basexmlvalidationresult_pkgvalidationresult_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basexmlvalidationresult",
            name="attribute",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Subject Attribute"
            ),
        ),
        migrations.AlterField(
            model_name="basexmlvalidationresult",
            name="parent",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Parent"
            ),
        ),
    ]
