# Generated by Django 5.0.3 on 2024-09-03 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0003_rename_critical_errors_package_blocking_errors_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="package",
            old_name="blocking_errors",
            new_name="critical_errors",
        ),
    ]
