# Generated by Django 5.0.3 on 2024-05-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0004_package_blocking_errors_package_errors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submetido"),
                    ("enqueued-for-validation", "Enqueued for validation"),
                    ("validated-with-errors", "Validated with errors"),
                    ("approved-with-errors", "Approved with errors"),
                    ("pending-correction", "Pending for correction"),
                    ("ready-to-be-finished", "Ready to be finished"),
                    ("quality-analysis", "Waiting for quality analysis"),
                    ("rejected", "Rejeitado"),
                    ("approved", "Aprovado"),
                    ("scheduled-for-publication", "Scheduled for publication"),
                    ("published", "Publicado"),
                ],
                default="enqueued-for-validation",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
