# Generated by Django 5.0.3 on 2024-04-12 11:56

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0004_basexmlvalidationresult_errornegativereaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationreport",
            name="conclusion",
            field=models.CharField(
                choices=[
                    ("", "no conclusion"),
                    ("rejected", "rejected"),
                    ("has-errors", "has-errors"),
                    ("approved", "approved"),
                ],
                default="",
                max_length=16,
                verbose_name="conclusion",
            ),
        ),
        migrations.AddField(
            model_name="xmlerrorreport",
            name="conclusion",
            field=models.CharField(
                choices=[
                    ("", "no conclusion"),
                    ("rejected", "rejected"),
                    ("has-errors", "has-errors"),
                    ("approved", "approved"),
                ],
                default="",
                max_length=16,
                verbose_name="conclusion",
            ),
        ),
        migrations.AddField(
            model_name="xmlinforeport",
            name="conclusion",
            field=models.CharField(
                choices=[
                    ("", "no conclusion"),
                    ("rejected", "rejected"),
                    ("has-errors", "has-errors"),
                    ("approved", "approved"),
                ],
                default="",
                max_length=16,
                verbose_name="conclusion",
            ),
        ),
        migrations.AlterField(
            model_name="errornegativereaction",
            name="error",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="non_error_justification",
                to="upload.xmlerror",
            ),
        ),
        migrations.AlterField(
            model_name="errornegativereactiondecision",
            name="error_negative_reaction",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qa_decision",
                to="upload.errornegativereaction",
            ),
        ),
        migrations.AlterField(
            model_name="pkgvalidationresult",
            name="report",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pkg_validation_result",
                to="upload.validationreport",
            ),
        ),
        migrations.AlterField(
            model_name="xmlinforeport",
            name="package",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xml_info_report",
                to="upload.package",
            ),
        ),
    ]
