# Generated by Django 5.0.3 on 2024-09-04 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0002_remove_articleauthor_author_and_more"),
        ("issue", "0004_issue_issue_pid_suffix_issue_order_toc_tocsection"),
        ("journal", "0005_alter_journal_official_journal"),
        ("package", "0003_remove_spspkg_components_remove_spspkg_scheduled_and_more"),
        ("team", "0001_initial"),
        ("upload", "0004_rename_blocking_errors_package_critical_errors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packagezip",
            name="files",
        ),
        migrations.RemoveField(
            model_name="packagezip",
            name="xmls",
        ),
        migrations.AddField(
            model_name="packagezip",
            name="name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(
                fields=["pkg_zip"], name="upload_pack_pkg_zip_7120f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packagezip",
            index=models.Index(fields=["name"], name="upload_pack_name_ba4e13_idx"),
        ),
    ]
