# Generated by Django 5.0.3 on 2024-05-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0005_alter_package_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="basexmlvalidationresult",
            name="parent_article_type",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Parent article type"
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submetido"),
                    ("enqueued-for-validation", "Enqueued for validation"),
                    ("validated-with-errors", "Validated with errors"),
                    ("approved-with-errors", "Approved with errors"),
                    ("pending-correction", "Pending for correction"),
                    ("quality-analysis", "Waiting for quality analysis"),
                    ("rejected", "Rejeitado"),
                    ("approved", "Aprovado"),
                    ("scheduled-for-publication", "Scheduled for publication"),
                    ("published", "Publicado"),
                ],
                default="enqueued-for-validation",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
