# Generated by Django 5.0.3 on 2024-09-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0005_remove_packagezip_files_remove_packagezip_xmls_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedPackage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("upload.package",),
        ),
        migrations.CreateModel(
            name="WorkInProgressPackage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("upload.package",),
        ),
        migrations.AlterField(
            model_name="package",
            name="xml_errors_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Error percentual",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="xml_warnings_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Warning percentual",
            ),
        ),
    ]
