# Generated by Django 5.0.3 on 2024-04-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0005_validationreport_conclusion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationreport",
            name="conclusion",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("rejected", "rejected"),
                    ("has-errors", "has-errors"),
                    ("approved", "approved"),
                ],
                default="",
                max_length=16,
                verbose_name="conclusion",
            ),
        ),
        migrations.AlterField(
            model_name="xmlerrorreport",
            name="conclusion",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("rejected", "rejected"),
                    ("has-errors", "has-errors"),
                    ("approved", "approved"),
                ],
                default="",
                max_length=16,
                verbose_name="conclusion",
            ),
        ),
        migrations.AlterField(
            model_name="xmlinforeport",
            name="conclusion",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("rejected", "rejected"),
                    ("has-errors", "has-errors"),
                    ("approved", "approved"),
                ],
                default="",
                max_length=16,
                verbose_name="conclusion",
            ),
        ),
    ]
