# Generated by Django 5.0.3 on 2024-05-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0006_basexmlvalidationresult_parent_article_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="qa_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approved-with-errors", "Approved with errors"),
                    ("pending-correction", "Pending for correction"),
                    ("rejected", "Rejeitado"),
                    ("approved", "Aprovado"),
                ],
                max_length=32,
                null=True,
                verbose_name="Quality analysis decision",
            ),
        ),
    ]
