# Generated by Django 5.0.3 on 2024-09-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0006_archivedpackage_workinprogresspackage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="linked",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related packages which will be published only if all are approved",
                null=True,
                to="upload.package",
                verbose_name="Related packages",
            ),
        ),
    ]
