# Generated by Django 5.0.3 on 2024-04-12 22:09

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0006_alter_validationreport_conclusion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basexmlvalidationresult",
            name="validation_type",
            field=models.CharField(max_length=32, verbose_name="Validation type"),
        ),
        migrations.AlterField(
            model_name="validationreport",
            name="package",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_report",
                to="upload.package",
            ),
        ),
        migrations.AlterField(
            model_name="xmlerror",
            name="report",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xml_error",
                to="upload.xmlerrorreport",
            ),
        ),
        migrations.AlterField(
            model_name="xmlerrorreport",
            name="package",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xml_error_report",
                to="upload.package",
            ),
        ),
        migrations.AlterField(
            model_name="xmlinfo",
            name="report",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xml_info",
                to="upload.xmlinforeport",
            ),
        ),
    ]
