# Generated by Django 5.0.3 on 2024-09-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0007_alter_package_linked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagezip",
            name="name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
