# Generated by Django 5.0.3 on 2024-04-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0008_package_name_xmlinforeport_file_alter_package_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationreport",
            name="category",
            field=models.CharField(
                choices=[
                    ("journal-incompatibility", "ARTICLE_JOURNAL_COMPATIBILITY"),
                    ("article-is-not-new", "ARTICLE_IS_NOT_NEW"),
                    ("xml-format", "XML_FORMAT"),
                    ("xml-style", "XML_STYLE"),
                    ("xml-content", "VAL_CAT_XML_CONTENT"),
                    ("group", "VAL_CAT_GROUP_DATA"),
                    ("bibliometrics-data", "BIBLIOMETRICS_DATA"),
                    ("services-data", "SERVICES_DATA"),
                    ("data-consistency", "DATA_CONSISTENCY"),
                    ("criteria-issues", "CRITERIA_ISSUES"),
                    ("asset", "ASSET"),
                    ("rendition", "RENDITION"),
                ],
                max_length=32,
                verbose_name="Validation category",
            ),
        ),
        migrations.AlterField(
            model_name="validationreport",
            name="conclusion",
            field=models.CharField(
                choices=[
                    ("done", "done"),
                    ("doing", "doing"),
                    ("", ""),
                    ("rejected", "rejected"),
                    ("has-errors", "has-errors"),
                    ("approved", "approved"),
                ],
                default="",
                max_length=16,
                verbose_name="conclusion",
            ),
        ),
        migrations.AlterField(
            model_name="xmlerrorreport",
            name="category",
            field=models.CharField(
                choices=[
                    ("journal-incompatibility", "ARTICLE_JOURNAL_COMPATIBILITY"),
                    ("article-is-not-new", "ARTICLE_IS_NOT_NEW"),
                    ("xml-format", "XML_FORMAT"),
                    ("xml-style", "XML_STYLE"),
                    ("xml-content", "VAL_CAT_XML_CONTENT"),
                    ("group", "VAL_CAT_GROUP_DATA"),
                    ("bibliometrics-data", "BIBLIOMETRICS_DATA"),
                    ("services-data", "SERVICES_DATA"),
                    ("data-consistency", "DATA_CONSISTENCY"),
                    ("criteria-issues", "CRITERIA_ISSUES"),
                    ("asset", "ASSET"),
                    ("rendition", "RENDITION"),
                ],
                max_length=32,
                verbose_name="Validation category",
            ),
        ),
        migrations.AlterField(
            model_name="xmlerrorreport",
            name="conclusion",
            field=models.CharField(
                choices=[
                    ("done", "done"),
                    ("doing", "doing"),
                    ("", ""),
                    ("rejected", "rejected"),
                    ("has-errors", "has-errors"),
                    ("approved", "approved"),
                ],
                default="",
                max_length=16,
                verbose_name="conclusion",
            ),
        ),
        migrations.AlterField(
            model_name="xmlinforeport",
            name="category",
            field=models.CharField(
                choices=[
                    ("journal-incompatibility", "ARTICLE_JOURNAL_COMPATIBILITY"),
                    ("article-is-not-new", "ARTICLE_IS_NOT_NEW"),
                    ("xml-format", "XML_FORMAT"),
                    ("xml-style", "XML_STYLE"),
                    ("xml-content", "VAL_CAT_XML_CONTENT"),
                    ("group", "VAL_CAT_GROUP_DATA"),
                    ("bibliometrics-data", "BIBLIOMETRICS_DATA"),
                    ("services-data", "SERVICES_DATA"),
                    ("data-consistency", "DATA_CONSISTENCY"),
                    ("criteria-issues", "CRITERIA_ISSUES"),
                    ("asset", "ASSET"),
                    ("rendition", "RENDITION"),
                ],
                max_length=32,
                verbose_name="Validation category",
            ),
        ),
        migrations.AlterField(
            model_name="xmlinforeport",
            name="conclusion",
            field=models.CharField(
                choices=[
                    ("done", "done"),
                    ("doing", "doing"),
                    ("", ""),
                    ("rejected", "rejected"),
                    ("has-errors", "has-errors"),
                    ("approved", "approved"),
                ],
                default="",
                max_length=16,
                verbose_name="conclusion",
            ),
        ),
    ]
