# Generated by Django 3.2.12 on 2023-02-20 03:54

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files_storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mensagem')),
                ('exception_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Exception Type')),
                ('exception_msg', models.CharField(blank=True, max_length=555, null=True, verbose_name='Exception Msg')),
                ('traceback', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='XMLDocPid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('v3', models.CharField(blank=True, max_length=23, null=True, verbose_name='v3')),
                ('v2', models.CharField(blank=True, max_length=23, null=True, verbose_name='v2')),
                ('aop_pid', models.CharField(blank=True, max_length=23, null=True, verbose_name='AOP PID')),
                ('fpage', models.CharField(blank=True, max_length=10, null=True, verbose_name='fpage')),
                ('fpage_seq', models.CharField(blank=True, max_length=10, null=True, verbose_name='fpage_seq')),
                ('lpage', models.CharField(blank=True, max_length=10, null=True, verbose_name='lpage')),
                ('article_publication_date', models.DateField(blank=True, null=True, verbose_name='Document Publication Date')),
                ('main_toc_section', models.CharField(blank=True, max_length=64, null=True, verbose_name='main_toc_section')),
                ('main_doi', models.CharField(blank=True, max_length=265, null=True, verbose_name='DOI')),
                ('z_elocation_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='elocation_id')),
                ('z_article_titles_texts', models.CharField(blank=True, max_length=64, null=True, verbose_name='article_titles_texts')),
                ('z_surnames', models.CharField(blank=True, max_length=64, null=True, verbose_name='surnames')),
                ('z_collab', models.CharField(blank=True, max_length=64, null=True, verbose_name='collab')),
                ('z_links', models.CharField(blank=True, max_length=64, null=True, verbose_name='links')),
                ('z_partial_body', models.CharField(blank=True, max_length=64, null=True, verbose_name='partial_body')),
                ('synchronized', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XMLIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_year', models.IntegerField(verbose_name='pub_year')),
                ('volume', models.CharField(blank=True, max_length=10, null=True, verbose_name='volume')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='number')),
                ('suppl', models.CharField(blank=True, max_length=10, null=True, verbose_name='suppl')),
            ],
        ),
        migrations.CreateModel(
            name='XMLJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='título')),
                ('issn_electronic', models.CharField(blank=True, max_length=9, null=True, verbose_name='issn_epub')),
                ('issn_print', models.CharField(blank=True, max_length=9, null=True, verbose_name='issn_ppub')),
            ],
        ),
        migrations.AddIndex(
            model_name='xmljournal',
            index=models.Index(fields=['issn_electronic'], name='xmlsps_xmlj_issn_el_e19709_idx'),
        ),
        migrations.AddIndex(
            model_name='xmljournal',
            index=models.Index(fields=['issn_print'], name='xmlsps_xmlj_issn_pr_778271_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xmljournal',
            unique_together={('issn_electronic', 'issn_print')},
        ),
        migrations.AddField(
            model_name='xmlissue',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xmlsps.xmljournal'),
        ),
        migrations.AddField(
            model_name='xmldocpid',
            name='aop_xml_versions',
            field=models.ManyToManyField(related_name='aop_xml_versions', to='files_storage.MinioFile'),
        ),
        migrations.AddField(
            model_name='xmldocpid',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='xmldocpid_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='xmldocpid',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xmlsps.xmlissue'),
        ),
        migrations.AddField(
            model_name='xmldocpid',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xmlsps.xmljournal'),
        ),
        migrations.AddField(
            model_name='xmldocpid',
            name='related_items',
            field=models.ManyToManyField(related_name='related_to', to='xmlsps.XMLDocPid'),
        ),
        migrations.AddField(
            model_name='xmldocpid',
            name='sync_failure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xmlsps.syncfailure'),
        ),
        migrations.AddField(
            model_name='xmldocpid',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xmldocpid_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='xmldocpid',
            name='xml_versions',
            field=models.ManyToManyField(related_name='xml_versions', to='files_storage.MinioFile'),
        ),
        migrations.AddField(
            model_name='syncfailure',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='syncfailure_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='syncfailure',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syncfailure_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['journal'], name='xmlsps_xmli_journal_eb6786_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['volume'], name='xmlsps_xmli_volume_e74246_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['number'], name='xmlsps_xmli_number_a4d54e_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['suppl'], name='xmlsps_xmli_suppl_59989c_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['pub_year'], name='xmlsps_xmli_pub_yea_a8c52f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xmlissue',
            unique_together={('journal', 'pub_year', 'volume', 'number', 'suppl')},
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['journal'], name='xmlsps_xmld_journal_a8f6f2_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['issue'], name='xmlsps_xmld_issue_i_43d6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['v3'], name='xmlsps_xmld_v3_ef07db_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['v2'], name='xmlsps_xmld_v2_e0d6a0_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['aop_pid'], name='xmlsps_xmld_aop_pid_407d64_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['fpage'], name='xmlsps_xmld_fpage_9c60fa_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['fpage_seq'], name='xmlsps_xmld_fpage_s_a54678_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['lpage'], name='xmlsps_xmld_lpage_246f98_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['article_publication_date'], name='xmlsps_xmld_article_f8bd76_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['main_toc_section'], name='xmlsps_xmld_main_to_e9d740_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['z_elocation_id'], name='xmlsps_xmld_z_eloca_afd9b4_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['main_doi'], name='xmlsps_xmld_main_do_36254b_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['z_article_titles_texts'], name='xmlsps_xmld_z_artic_6d4d10_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['z_surnames'], name='xmlsps_xmld_z_surna_54c64f_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['z_collab'], name='xmlsps_xmld_z_colla_f5ddbf_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['z_links'], name='xmlsps_xmld_z_links_665fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['z_partial_body'], name='xmlsps_xmld_z_parti_8b732b_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['synchronized'], name='xmlsps_xmld_synchro_6ab8a4_idx'),
        ),
        migrations.AddIndex(
            model_name='xmldocpid',
            index=models.Index(fields=['sync_failure'], name='xmlsps_xmld_sync_fa_452a54_idx'),
        ),
    ]
