# Generated by Django 3.2.12 on 2023-01-13 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files_storage', '0005_delete_fileversions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncodedXMLArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('v3', models.CharField(blank=True, max_length=23, null=True, verbose_name='v3')),
                ('v2', models.CharField(blank=True, max_length=23, null=True, verbose_name='v2')),
                ('aop_pid', models.CharField(blank=True, max_length=23, null=True, verbose_name='AOP PID')),
                ('fpage', models.CharField(blank=True, max_length=10, null=True, verbose_name='fpage')),
                ('fpage_seq', models.CharField(blank=True, max_length=10, null=True, verbose_name='fpage_seq')),
                ('lpage', models.CharField(blank=True, max_length=10, null=True, verbose_name='lpage')),
                ('article_publication_date', models.DateField(blank=True, null=True, verbose_name='Document Publication Date')),
                ('z_elocation_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='elocation_id')),
                ('z_main_doi', models.CharField(blank=True, max_length=64, null=True, verbose_name='DOI')),
                ('z_main_toc_section', models.CharField(blank=True, max_length=64, null=True, verbose_name='main_toc_section')),
                ('z_article_titles_texts', models.CharField(blank=True, max_length=64, null=True, verbose_name='article_titles_texts')),
                ('z_surnames', models.CharField(blank=True, max_length=64, null=True, verbose_name='surnames')),
                ('z_collab', models.CharField(blank=True, max_length=64, null=True, verbose_name='collab')),
                ('z_links', models.CharField(blank=True, max_length=64, null=True, verbose_name='links')),
                ('z_partial_body', models.CharField(blank=True, max_length=64, null=True, verbose_name='partial_body')),
                ('synchronized', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XMLArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
            ],
        ),
        migrations.CreateModel(
            name='XMLIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_year', models.IntegerField(verbose_name='pub_year')),
                ('volume', models.CharField(blank=True, max_length=10, null=True, verbose_name='volume')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='number')),
                ('suppl', models.CharField(blank=True, max_length=10, null=True, verbose_name='suppl')),
            ],
        ),
        migrations.CreateModel(
            name='XMLJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='título')),
                ('issn_electronic', models.CharField(blank=True, max_length=9, null=True, verbose_name='issn_epub')),
                ('issn_print', models.CharField(blank=True, max_length=9, null=True, verbose_name='issn_ppub')),
            ],
        ),
        migrations.AddIndex(
            model_name='xmljournal',
            index=models.Index(fields=['issn_electronic'], name='xmlsps_xmlj_issn_el_e19709_idx'),
        ),
        migrations.AddIndex(
            model_name='xmljournal',
            index=models.Index(fields=['issn_print'], name='xmlsps_xmlj_issn_pr_778271_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xmljournal',
            unique_together={('issn_electronic', 'issn_print')},
        ),
        migrations.AddField(
            model_name='xmlissue',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xmlsps.xmljournal'),
        ),
        migrations.AddField(
            model_name='xmlarticle',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='xmlarticle_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='xmlarticle',
            name='encoded_xml',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xmlsps.encodedxmlarticle'),
        ),
        migrations.AddField(
            model_name='xmlarticle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xmlarticle_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='encodedxmlarticle',
            name='aop_xml_versions',
            field=models.ManyToManyField(related_name='aop_xml_versions', to='files_storage.MinioFile'),
        ),
        migrations.AddField(
            model_name='encodedxmlarticle',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='encodedxmlarticle_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='encodedxmlarticle',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xmlsps.xmlissue'),
        ),
        migrations.AddField(
            model_name='encodedxmlarticle',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xmlsps.xmljournal'),
        ),
        migrations.AddField(
            model_name='encodedxmlarticle',
            name='related_items',
            field=models.ManyToManyField(related_name='related_to', to='xmlsps.EncodedXMLArticle'),
        ),
        migrations.AddField(
            model_name='encodedxmlarticle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encodedxmlarticle_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
        migrations.AddField(
            model_name='encodedxmlarticle',
            name='xml_versions',
            field=models.ManyToManyField(related_name='xml_versions', to='files_storage.MinioFile'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['journal'], name='xmlsps_xmli_journal_eb6786_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['volume'], name='xmlsps_xmli_volume_e74246_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['number'], name='xmlsps_xmli_number_a4d54e_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['suppl'], name='xmlsps_xmli_suppl_59989c_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlissue',
            index=models.Index(fields=['pub_year'], name='xmlsps_xmli_pub_yea_a8c52f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='xmlissue',
            unique_together={('journal', 'pub_year', 'volume', 'number', 'suppl')},
        ),
        migrations.AddIndex(
            model_name='xmlarticle',
            index=models.Index(fields=['encoded_xml'], name='xmlsps_xmla_encoded_ef367a_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['journal'], name='xmlsps_enco_journal_6768c9_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['issue'], name='xmlsps_enco_issue_i_6fce33_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['v3'], name='xmlsps_enco_v3_23197e_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['v2'], name='xmlsps_enco_v2_33ba24_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['aop_pid'], name='xmlsps_enco_aop_pid_3c0092_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['fpage'], name='xmlsps_enco_fpage_cc9527_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['fpage_seq'], name='xmlsps_enco_fpage_s_832146_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['lpage'], name='xmlsps_enco_lpage_6ebd04_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['article_publication_date'], name='xmlsps_enco_article_590bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['z_elocation_id'], name='xmlsps_enco_z_eloca_321d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['z_main_doi'], name='xmlsps_enco_z_main__1d0b74_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['z_main_toc_section'], name='xmlsps_enco_z_main__4ec205_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['z_article_titles_texts'], name='xmlsps_enco_z_artic_420ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['z_surnames'], name='xmlsps_enco_z_surna_e5c7fc_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['z_collab'], name='xmlsps_enco_z_colla_56b7db_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['z_links'], name='xmlsps_enco_z_links_65d8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['z_partial_body'], name='xmlsps_enco_z_parti_cdac05_idx'),
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['synchronized'], name='xmlsps_enco_synchro_cba5ea_idx'),
        ),
    ]
