# Generated by Django 3.2.12 on 2023-01-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlsps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='encodedxmlarticle',
            name='xmlsps_enco_z_main__4ec205_idx',
        ),
        migrations.RenameField(
            model_name='encodedxmlarticle',
            old_name='z_main_toc_section',
            new_name='main_toc_section',
        ),
        migrations.AddIndex(
            model_name='encodedxmlarticle',
            index=models.Index(fields=['main_toc_section'], name='xmlsps_enco_main_to_689ebb_idx'),
        ),
    ]
