# Generated by Django 3.2.12 on 2023-02-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_storage', '0001_initial'),
        ('xmlsps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLVersion',
            fields=[
                ('miniofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files_storage.miniofile')),
                ('finger_print', models.CharField(blank=True, max_length=65, null=True)),
            ],
            bases=('files_storage.miniofile',),
        ),
        migrations.AddIndex(
            model_name='xmlversion',
            index=models.Index(fields=['finger_print'], name='xmlsps_xmlv_finger__c27ac5_idx'),
        ),
        migrations.AlterField(
            model_name='xmldocpid',
            name='aop_xml_versions',
            field=models.ManyToManyField(related_name='aop_xml_versions', to='xmlsps.XMLVersion'),
        ),
        migrations.AlterField(
            model_name='xmldocpid',
            name='xml_versions',
            field=models.ManyToManyField(related_name='xml_versions', to='xmlsps.XMLVersion'),
        ),
    ]
