# Generated by Django 3.2.12 on 2023-01-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlsps', '0003_auto_20230113_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='encodedxmlarticle',
            name='received_xml',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Zip XML File'),
        ),
    ]
