# Generated by Django 3.2.12 on 2023-01-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmlsps', '0004_encodedxmlarticle_received_xml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encodedxmlarticle',
            name='received_xml',
        ),
    ]
