# Generated by Django 5.0.3 on 2024-06-06 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pid_provider", "0003_pidproviderendpoint"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PidProviderEndpoint",
        ),
    ]
