# Generated by Django 3.2.12 on 2023-01-06 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files_storage', '0005_delete_fileversions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pid_provider', '0005_auto_20221231_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='AOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('aop_pid', models.CharField(blank=True, max_length=23, null=True, verbose_name='aop_pid')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='aop_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aop_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
                ('versions', models.ManyToManyField(to='files_storage.MinioFile')),
            ],
        ),
        migrations.AlterField(
            model_name='basearticle',
            name='article_titles_texts',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='article_titles_texts'),
        ),
        migrations.AlterField(
            model_name='basearticle',
            name='collab',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='collab'),
        ),
        migrations.AlterField(
            model_name='basearticle',
            name='elocation_id',
            field=models.CharField(blank=True, max_length=23, null=True, verbose_name='elocation_id'),
        ),
        migrations.AlterField(
            model_name='basearticle',
            name='links',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='links'),
        ),
        migrations.AlterField(
            model_name='basearticle',
            name='main_doi',
            field=models.CharField(blank=True, max_length=265, null=True, verbose_name='main_doi'),
        ),
        migrations.AlterField(
            model_name='basearticle',
            name='partial_body',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='partial_body'),
        ),
        migrations.AlterField(
            model_name='basearticle',
            name='surnames',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='surnames'),
        ),
        migrations.AlterField(
            model_name='basearticle',
            name='v3',
            field=models.CharField(blank=True, max_length=23, null=True, verbose_name='v3'),
        ),
        migrations.AlterField(
            model_name='xmlaoparticle',
            name='aop_pid',
            field=models.CharField(blank=True, max_length=23, null=True, verbose_name='aop_pid'),
        ),
        migrations.AlterField(
            model_name='xmlaoparticle',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_provider.xmljournal'),
        ),
        migrations.AlterField(
            model_name='xmlaoparticle',
            name='published_in_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_provider.xmlarticle'),
        ),
        migrations.AlterField(
            model_name='xmlarticle',
            name='fpage',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='fpage'),
        ),
        migrations.AlterField(
            model_name='xmlarticle',
            name='fpage_seq',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='fpage_seq'),
        ),
        migrations.AlterField(
            model_name='xmlarticle',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_provider.xmlissue'),
        ),
        migrations.AlterField(
            model_name='xmlarticle',
            name='lpage',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='lpage'),
        ),
        migrations.AlterField(
            model_name='xmlarticle',
            name='v2',
            field=models.CharField(blank=True, max_length=23, null=True, verbose_name='v2'),
        ),
        migrations.AlterField(
            model_name='xmlissue',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_provider.xmljournal'),
        ),
        migrations.AlterField(
            model_name='xmlissue',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='xmlissue',
            name='suppl',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='suppl'),
        ),
        migrations.AlterField(
            model_name='xmlissue',
            name='volume',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='volume'),
        ),
        migrations.AlterField(
            model_name='xmljournal',
            name='issn_electronic',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='issn_epub'),
        ),
        migrations.AlterField(
            model_name='xmljournal',
            name='issn_print',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='issn_ppub'),
        ),
        migrations.CreateModel(
            name='VOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('v2', models.CharField(blank=True, max_length=23, null=True, verbose_name='v2')),
                ('fpage', models.CharField(blank=True, max_length=10, null=True, verbose_name='fpage')),
                ('fpage_seq', models.CharField(blank=True, max_length=10, null=True, verbose_name='fpage_seq')),
                ('lpage', models.CharField(blank=True, max_length=10, null=True, verbose_name='lpage')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vor_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_provider.xmlissue')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vor_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.CreateModel(
            name='PidV3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('v3', models.CharField(blank=True, max_length=23, null=True, verbose_name='v3')),
                ('main_doi', models.CharField(blank=True, max_length=265, null=True, verbose_name='main_doi')),
                ('elocation_id', models.CharField(blank=True, max_length=23, null=True, verbose_name='elocation_id')),
                ('article_titles_texts', models.CharField(blank=True, max_length=64, null=True, verbose_name='article_titles_texts')),
                ('surnames', models.CharField(blank=True, max_length=64, null=True, verbose_name='surnames')),
                ('collab', models.CharField(blank=True, max_length=64, null=True, verbose_name='collab')),
                ('links', models.CharField(blank=True, max_length=64, null=True, verbose_name='links')),
                ('partial_body', models.CharField(blank=True, max_length=64, null=True, verbose_name='partial_body')),
                ('aop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_provider.aop')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pidv3_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_provider.xmljournal')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pidv3_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
                ('vor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pid_provider.vor')),
            ],
        ),
        migrations.AddIndex(
            model_name='vor',
            index=models.Index(fields=['v2'], name='pid_provide_v2_e971af_idx'),
        ),
        migrations.AddIndex(
            model_name='vor',
            index=models.Index(fields=['issue'], name='pid_provide_issue_i_dfb858_idx'),
        ),
        migrations.AddIndex(
            model_name='vor',
            index=models.Index(fields=['fpage'], name='pid_provide_fpage_41a450_idx'),
        ),
        migrations.AddIndex(
            model_name='vor',
            index=models.Index(fields=['fpage_seq'], name='pid_provide_fpage_s_961628_idx'),
        ),
        migrations.AddIndex(
            model_name='vor',
            index=models.Index(fields=['lpage'], name='pid_provide_lpage_3cf273_idx'),
        ),
        migrations.AddIndex(
            model_name='pidv3',
            index=models.Index(fields=['v3'], name='pid_provide_v3_dfc14d_idx'),
        ),
        migrations.AddIndex(
            model_name='pidv3',
            index=models.Index(fields=['aop'], name='pid_provide_aop_id_fd3b47_idx'),
        ),
        migrations.AddIndex(
            model_name='pidv3',
            index=models.Index(fields=['vor'], name='pid_provide_vor_id_5c893f_idx'),
        ),
        migrations.AddIndex(
            model_name='pidv3',
            index=models.Index(fields=['main_doi'], name='pid_provide_main_do_cbad5f_idx'),
        ),
        migrations.AddIndex(
            model_name='pidv3',
            index=models.Index(fields=['article_titles_texts'], name='pid_provide_article_288df1_idx'),
        ),
        migrations.AddIndex(
            model_name='pidv3',
            index=models.Index(fields=['surnames'], name='pid_provide_surname_8292f9_idx'),
        ),
        migrations.AddIndex(
            model_name='pidv3',
            index=models.Index(fields=['collab'], name='pid_provide_collab_0ad9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='pidv3',
            index=models.Index(fields=['links'], name='pid_provide_links_389bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='pidv3',
            index=models.Index(fields=['partial_body'], name='pid_provide_partial_024d33_idx'),
        ),
        migrations.AddIndex(
            model_name='pidv3',
            index=models.Index(fields=['elocation_id'], name='pid_provide_elocati_5c7fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='aop',
            index=models.Index(fields=['aop_pid'], name='pid_provide_aop_pid_06ba67_idx'),
        ),
    ]
