# Generated by Django 3.2.12 on 2023-01-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_storage', '0005_delete_fileversions'),
        ('pid_provider', '0006_auto_20230106_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='vor',
            name='versions',
            field=models.ManyToManyField(to='files_storage.MinioFile'),
        ),
    ]
