# Generated by Django 3.2.12 on 2023-01-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_provider', '0008_pidv3_synchronized'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmljournal',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='título'),
        ),
    ]
