# Generated by Django 3.2.12 on 2023-01-26 23:23

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20230126_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('basename', models.URLField(blank=True, max_length=255, null=True, verbose_name='Basename')),
                ('uri', models.URLField(blank=True, max_length=255, null=True, verbose_name='URI')),
                ('finger_print', models.CharField(blank=True, max_length=64, null=True, verbose_name='Finger print')),
                ('creator', models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='miniofile_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miniofile_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.CreateModel(
            name='SciELOFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('pkg_name', models.CharField(blank=True, max_length=65, null=True, verbose_name='Package name')),
                ('relative_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relative Path')),
                ('creator', models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='scielofile_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('langs', models.ManyToManyField(to='core.Language')),
                ('remote_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_storage.miniofile')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scielofile_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.CreateModel(
            name='AssetFile',
            fields=[
                ('scielofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files_storage.scielofile')),
                ('is_supplementary_material', models.BooleanField(default=False)),
            ],
            bases=('files_storage.scielofile',),
        ),
        migrations.CreateModel(
            name='FileWithLang',
            fields=[
                ('scielofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files_storage.scielofile')),
            ],
            bases=('files_storage.scielofile',),
        ),
        migrations.CreateModel(
            name='MinioConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('host', models.CharField(blank=True, max_length=255, null=True, verbose_name='Host')),
                ('bucket_root', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bucket root')),
                ('bucket_app_subdir', models.CharField(blank=True, max_length=64, null=True, verbose_name='Bucket app subdir')),
                ('access_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Access key')),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret key')),
                ('secure', models.BooleanField(default=True, verbose_name='Secure')),
                ('creator', models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='minioconfiguration_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minioconfiguration_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
        ),
        migrations.CreateModel(
            name='SciELOHTMLFile',
            fields=[
                ('filewithlang_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files_storage.filewithlang')),
                ('part', models.CharField(max_length=6, verbose_name='Part')),
            ],
            bases=('files_storage.filewithlang',),
        ),
        migrations.CreateModel(
            name='XMLFile',
            fields=[
                ('filewithlang_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files_storage.filewithlang')),
            ],
            options={
                'abstract': False,
            },
            bases=('files_storage.filewithlang',),
        ),
        migrations.AddIndex(
            model_name='scielofile',
            index=models.Index(fields=['pkg_name'], name='files_stora_pkg_nam_203eea_idx'),
        ),
        migrations.AddIndex(
            model_name='scielofile',
            index=models.Index(fields=['relative_path'], name='files_stora_relativ_fcf704_idx'),
        ),
        migrations.AddIndex(
            model_name='scielofile',
            index=models.Index(fields=['remote_file'], name='files_stora_remote__f9893f_idx'),
        ),
        migrations.AddIndex(
            model_name='miniofile',
            index=models.Index(fields=['basename'], name='files_stora_basenam_9cfe44_idx'),
        ),
        migrations.AddIndex(
            model_name='miniofile',
            index=models.Index(fields=['creator'], name='files_stora_creator_fefb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='miniofile',
            index=models.Index(fields=['created'], name='files_stora_created_964deb_idx'),
        ),
        migrations.AddIndex(
            model_name='miniofile',
            index=models.Index(fields=['finger_print'], name='files_stora_finger__d77bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='minioconfiguration',
            index=models.Index(fields=['name'], name='files_stora_name_6664a8_idx'),
        ),
        migrations.AddIndex(
            model_name='minioconfiguration',
            index=models.Index(fields=['host'], name='files_stora_host_12e098_idx'),
        ),
        migrations.AddIndex(
            model_name='minioconfiguration',
            index=models.Index(fields=['bucket_root'], name='files_stora_bucket__8a0a27_idx'),
        ),
        migrations.AddIndex(
            model_name='minioconfiguration',
            index=models.Index(fields=['bucket_app_subdir'], name='files_stora_bucket__fb2096_idx'),
        ),
        migrations.AddField(
            model_name='filewithlang',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language'),
        ),
        migrations.AddIndex(
            model_name='assetfile',
            index=models.Index(fields=['is_supplementary_material'], name='files_stora_is_supp_b943c1_idx'),
        ),
        migrations.CreateModel(
            name='BodyAndBackXMLFile',
            fields=[
                ('xmlfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files_storage.xmlfile')),
                ('selected', models.BooleanField(default=False)),
                ('version', models.IntegerField(blank=True, null=True, verbose_name='Version')),
            ],
            options={
                'abstract': False,
            },
            bases=('files_storage.xmlfile',),
        ),
        migrations.AddField(
            model_name='xmlfile',
            name='assets_files',
            field=models.ManyToManyField(to='files_storage.AssetFile'),
        ),
        migrations.AddField(
            model_name='scielohtmlfile',
            name='assets_files',
            field=models.ManyToManyField(to='files_storage.AssetFile'),
        ),
        migrations.AddIndex(
            model_name='filewithlang',
            index=models.Index(fields=['lang'], name='files_stora_lang_id_ab3021_idx'),
        ),
        migrations.AddIndex(
            model_name='scielohtmlfile',
            index=models.Index(fields=['part'], name='files_stora_part_6e8d26_idx'),
        ),
    ]
