# Generated by Django 3.2.12 on 2023-01-26 23:23

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doiwithlang',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=models.SET(core.models.get_sentinel_user), related_name='doiwithlang_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='doiwithlang',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doiwithlang_last_mod_user', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
    ]
